figure(1); clf; hold on
yyaxis left
data = importfile('iv_curve.csv')
plot(data.voltageV, data.currentmA, '.')
xlim([0 inf])
ylim([ 0 inf])
xlabel('voltage, V')
ylabel('current, mA')
% set(gca,'Xlim',[0 limsx(2)]);

power = data.voltageV.*data.currentmA;
% figure(2); clf; hold on; 
yyaxis right
plot(data.voltageV, power, '.')


function ivcurve = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  IVCURVE = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  IVCURVE = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  ivcurve = importfile("C:\Users\Jordan.Firth\OneDrive - afacademy.af.edu\Documents\Astro-331X-2023\lab_01_electrical_power\iv_curve.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Jul-2023 00:19:51

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["timems", "currentmA", "voltageV"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ivcurve = readtable(filename, opts);

end % function importfile

